CC = gcc
CFLAGS = -Wall -Wextra -pedantic
TARGET = e-p6
SRCS = e-p6.c
OBJS = $(SRCS:.c=.o)

all: $(TARGET)

$(TARGET): $(OBJS)
  $(CC) $(CFLAGS) -o $@ $^

%.o: %.c
  $(CC) $(CFLAGS) -c $< -o $@

clean:
  rm -f $(OBJS) $(TARGET)
